#!/bin/bash

# 사용할 BCM GPIO 핀 번호
PINS=(22 23 24 25)

# 무한 루프
while true
do
    for PIN in "${PINS[@]}"
    do
        # 해당 핀 ON
        gpioset gpiochip0 $PIN=1
        sleep 1
        # 해당 핀 OFF
        gpioset gpiochip0 $PIN=0
    done
done
