#!/bin/bash

# 사용할 BCM 핀들: LSB부터 [22, 23, 24]
PINS=(22 23 24)

# 초기화 (출력모드 설정은 gpiod에서는 필요 없음)

while true
do
    for i in {0..7}
    do
        # 각 비트값 추출
        for j in {0..2}
        do
            VALUE=$(( (i >> j) & 1 ))
            gpioset gpiochip0 ${PINS[$j]}=$VALUE
        done
        sleep 1
    done
done
